# Generated by Django 4.2.3 on 2023-08-14 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_agent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='employment_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='marital_status',
        ),
        migrations.CreateModel(
            name='BorrowerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employment_status', models.CharField(blank=True, choices=[('Employed', 'Employed'), ('Unemployed', 'Unemployed'), ('Self Employed', 'Self Employed'), ('Student', 'Student'), ('Retired', 'Retired'), ('Other', 'Other')], max_length=50, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('Married', 'Married'), ('Single', 'Single')], max_length=50, null=True)),
                ('education', models.CharField(blank=True, choices=[('Primary School', 'Primary School'), ('Secondary School', 'Secondary School'), ('University', 'University'), ('Other', 'Other')], max_length=50, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.agents')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
