# Generated by Django 4.2.3 on 2023-08-18 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_agent_remove_profile_education_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowerprofile',
            options={'verbose_name': 'Borrower Profile', 'verbose_name_plural': 'Borrower Profile'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='paybillno',
        ),
        migrations.CreateModel(
            name='LenderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paybillno', models.CharField(blank=True, max_length=50, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lender Profile',
                'verbose_name_plural': 'Lender Profile',
            },
        ),
    ]
