# Generated by Django 4.2.3 on 2023-08-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_borrowerprofile_options_remove_profile_brand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowerprofile',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='borrowerprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lenderprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Agents',
        ),
        migrations.DeleteModel(
            name='BorrowerProfile',
        ),
        migrations.DeleteModel(
            name='LenderProfile',
        ),
    ]
