# Generated by Django 4.2.3 on 2023-08-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_borrowerprofile_agent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='alternative_mobile_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referer_mobile_number',
        ),
    ]
