# Generated by Django 4.2.3 on 2023-09-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_profile_monthly_income'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='nationa_id',
            new_name='national_id',
        ),
    ]
