# Generated by Django 4.2.3 on 2023-08-21 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0002_loanapplications'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplications',
            name='remarks',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
