# Generated by Django 4.2.3 on 2023-08-27 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0003_loanapplications_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanproduct',
            old_name='min_duration',
            new_name='repayment_term',
        ),
    ]
