# Generated by Django 4.2.3 on 2023-08-27 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0004_rename_min_duration_loanproduct_repayment_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='modified_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='loanproduct',
            name='product_description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
