# Generated by Django 4.2.3 on 2023-08-27 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0006_alter_loanproduct_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanproduct',
            name='penalties',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
