# Generated by Django 4.2.3 on 2023-09-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0008_loanproduct_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
