# Generated by Django 4.2.3 on 2023-09-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0009_alter_loanproduct_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenderprofile',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lenderprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lenderprofile',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lenderprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lenderprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
