# Generated by Django 4.2.3 on 2023-09-09 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0010_lenderprofile_address_lenderprofile_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lenderprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='lenderprofile',
            name='postal_code',
        ),
    ]
