# Generated by Django 4.2.3 on 2023-09-09 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0011_remove_lenderprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lenderprofile',
            name='country',
            field=models.CharField(blank=True, default='Kenya', max_length=50, null=True),
        ),
    ]
