# Generated by Django 4.2.3 on 2023-09-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0013_lenderprofile_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenderprofile',
            name='lending_mobile_no',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
