# Generated by Django 4.2.3 on 2023-09-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0014_lenderprofile_lending_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenderprofile',
            name='lending_as',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
