# Generated by Django 4.2.3 on 2023-09-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0015_lenderprofile_lending_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='lenderprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=50, null=True),
        ),
    ]
