# Generated by Django 4.2.3 on 2023-10-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0016_lenderprofile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanapplications',
            name='loan_amount',
        ),
        migrations.AddField(
            model_name='loanapplications',
            name='fees',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplications',
            name='interest',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplications',
            name='principle',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplications',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
