# Generated by Django 4.2.3 on 2023-11-01 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lenders', '0018_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('Loan Disbursement', 'Loan Disbursement'), ('Charges', 'Charges'), ('Payment', 'Payment')], max_length=20)),
                ('transaction_date', models.DateTimeField()),
                ('debit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenders.lenderprofile')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenders.loanproduct')),
            ],
            options={
                'ordering': ['transaction_date'],
            },
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
