# Generated by Django 4.2.3 on 2023-11-01 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0019_transaction_delete_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoansCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_loans', models.IntegerField(default=0)),
                ('approved_loans', models.IntegerField(default=0)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('modified_on', models.DateField(auto_now=True)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lenders.lenderprofile')),
            ],
            options={
                'verbose_name': 'Loan Counter',
                'verbose_name_plural': 'Loans Counter',
            },
        ),
    ]
