# Generated by Django 4.2.3 on 2023-11-05 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0020_loanscounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
