# Generated by Django 4.2.3 on 2023-08-18 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('interest_rate', models.CharField(blank=True, max_length=50, null=True)),
                ('min_loan_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('max_loan_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('min_duration', models.CharField(blank=True, max_length=50, null=True)),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.lenderprofile')),
            ],
        ),
    ]
