# Generated by Django 4.2.3 on 2023-08-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_loanproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanproduct',
            name='interest_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
