# Generated by Django 4.2.3 on 2023-08-21 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0001_initial'),
        ('management', '0004_borrowerprofile_alternative_mobile_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lenderprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='loanproduct',
            name='lender',
        ),
        migrations.AddField(
            model_name='borrowerprofile',
            name='interest_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowerprofile',
            name='lender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lenders.lenderprofile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='borrowerprofile',
            name='max_loan_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowerprofile',
            name='min_duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowerprofile',
            name='min_loan_amount',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowerprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='borrowerprofile',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lenders.agents'),
        ),
        migrations.DeleteModel(
            name='Agents',
        ),
        migrations.DeleteModel(
            name='LenderProfile',
        ),
        migrations.DeleteModel(
            name='LoanProduct',
        ),
    ]
