# Generated by Django 4.2.3 on 2023-09-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_remove_lenderprofile_user_remove_loanproduct_lender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowerProfile',
        ),
    ]
