# Generated by Django 4.2.3 on 2023-09-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowerprofile',
            name='interest_rate',
        ),
        migrations.RemoveField(
            model_name='borrowerprofile',
            name='max_loan_amount',
        ),
        migrations.RemoveField(
            model_name='borrowerprofile',
            name='min_duration',
        ),
        migrations.RemoveField(
            model_name='borrowerprofile',
            name='min_loan_amount',
        ),
        migrations.RemoveField(
            model_name='borrowerprofile',
            name='name',
        ),
        migrations.AddField(
            model_name='borrowerprofile',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50, null=True),
        ),
    ]
