# Generated by Django 4.2.3 on 2023-09-19 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lenders', '0016_lenderprofile_status'),
        ('borrow', '0002_remove_borrowerprofile_interest_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowerprofile',
            name='lender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lenders.lenderprofile'),
        ),
    ]
