# Generated by Django 4.2.3 on 2023-09-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_alter_borrowerprofile_lender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowerprofile',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('employed', 'Employed'), ('unemployed', 'Unemployed'), ('self-employed', 'Self Employed'), ('student', 'Student'), ('retired', 'Retired'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
