# Generated by Django 4.2.3 on 2023-09-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0005_alter_borrowerprofile_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowerprofile',
            name='income_range',
            field=models.CharField(blank=True, choices=[('1', '0-10,000'), ('2', '10,000-20,000'), ('3', '20,000-30,000'), ('4', '30,000-40,000'), ('5', '40,000-50,000'), ('6', 'Above 50,000')], max_length=50, null=True),
        ),
    ]
