# Generated by Django 4.2.3 on 2023-09-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0006_borrowerprofile_income_range'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowerprofile',
            name='country',
            field=models.CharField(blank=True, default='Kenya', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowerprofile',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowerprofile',
            name='employment_sector',
            field=models.CharField(blank=True, choices=[('agriculture', 'Agriculture'), ('manufacturing', 'Manufacturing'), ('services', 'Services'), ('construction', 'Construction'), ('retail', 'Retail'), ('wholesale', 'Wholesale'), ('transport', 'Transport'), ('education', 'Education'), ('health', 'Health'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='borrowerprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
