# Generated by Django 4.2.3 on 2023-09-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0007_borrowerprofile_country_borrowerprofile_county_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowerprofile',
            name='education',
            field=models.CharField(blank=True, choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('tertiary', 'Tertiary'), ('university', 'University'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
