# Generated by Django 4.2.3 on 2023-09-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0008_alter_borrowerprofile_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowerprofile',
            name='loan_limit',
            field=models.CharField(default=0, max_length=50, null=True),
        ),
    ]
