# Generated by Django 4.2.3 on 2023-11-05 03:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('borrow', '0009_borrowerprofile_loan_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(blank=True, choices=[('borrower', 'Borrower'), ('lender', 'Lender'), ('admin', 'Admin')], max_length=50, null=True)),
                ('type', models.CharField(blank=True, choices=[('loan_disbursement', 'Loan Disbursement'), ('loan_repayment', 'Loan Repayment')], max_length=50, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
